export const validLangs = () => {
        return{
        "arb": "arb",
        "ar-en": "ar-AE",
        "ca-es":"ca-ES", 
        "yue-cn":"yue-CN",
        "cmn-cn":"cmn-CN",
        "da-dk":"da-DK",
        "nl-nk":"nl-NL",
        "en-au":"en-AU",
        "en-gb":"en-GB",
        "en-in":"en-IN",
        "en-nz":"en-NZ",
        "en-za":"en-ZA",
        "en-us":"en-US",
        "en-gb-wls": "en-GB-WLS",
        "fi-fi":"fi-FI",
        "fr-fr":"fr-FR",
        "fr-ca":"fr-CA",
        "hi-in":"hi-IN",
        "de-de":"de-DE",
        "de-at":"de-AT",
        "is-is":"is-IS",
        "it-it":"it-IT",
        "ja-jp":"ja-JP",
        "ko-kr":"ko-KR",
        "nb-no":"nb-NO",
        "pl-pl":"pl-PL",
        "pt-br":"pt-BR",
        "pt-pt":"pt-PT",
        "ro-ro":"ro-RO",
        "ru-ru":"ru-RU",
        "es-es":"es-ES",
        "es-mx":"es-MX",
        "es-us":"es-US",
        "sv-se":"sv-SE",
        "tr-tr":"tr-TR",
        "cy-gb":"cy-GB"
    }
}
